trigger: none

pool:
  name: dev-aks-akkc-agent

stages:

# ==========================
# Test Stage
# ==========================
- stage: Test
  displayName: Test Stage
  jobs:
  - job: Test
    displayName: Test Pipeline
    steps:
    - checkout: self
    - script: |
        echo "Deployment Starting..."
        ls -R $(Build.SourcesDirectory)
      displayName: Verify Repository

# ==========================
# Deploy Stage
# ==========================
- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Test
  condition: succeeded()

  jobs:
  - deployment: DeployToAKS
    displayName: Deploy to AKS

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: self

          - task: KubernetesManifest@1
            displayName: Deploy Manifests
            inputs:
              action: deploy
              connectionType: Kubernetes Service Connection
              kubernetesServiceConnection: dev-connection
              namespace: cicd-dev
              manifests: |
                $(Build.SourcesDirectory)/manifests/infra/infra-configmap.yaml
                $(Build.SourcesDirectory)/manifests/infra/infra-deploy.yaml
                $(Build.SourcesDirectory)/manifests/infra/infra-svc.yaml
                $(Build.SourcesDirectory)/manifests/vm/vm-svc.yaml
                $(Build.SourcesDirectory)/manifests/vm/vm-configmap.yaml
                $(Build.SourcesDirectory)/manifests/vm/vm-deploy.yaml
                $(Build.SourcesDirectory)/manifests/stg/stg-svc.yaml
                $(Build.SourcesDirectory)/manifests/stg/stg-configmap.yaml
                $(Build.SourcesDirectory)/manifests/stg/stg-deploy.yaml
                $(Build.SourcesDirectory)/manifests/ingress.yaml
