
trigger: none

pool: dev-aks-akkc-agent


stages:
- stage: Deploy
  jobs:
  - deployment: DeployToAKS
    displayName: Deploy to AKS

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - task: KubernetesManifest@1
            inputs:
              action: deploy
              connectionType: Kubernetes Service Connection
              kubernetesServiceConnection: dev-connection
              namespace: cicd-dev
              manifests: |
                $(Build.SourcesDirectory)/manifests/deployments.yaml
                $(Build.SourcesDirectory)/manifests/svc.yaml
                $(Build.SourcesDirectory)/manifests/configmap.yaml
                $(Build.SourcesDirectory)/manifests/agic-ingress.yaml


